In [37]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
import numpy as np 

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [38]:
df = pd.read_csv("creditcard_cleaned.csv")

In [39]:
df.head()

Unnamed: 0  scaled_amount  scaled_time         V1         V2         V3  \
0        7418      -0.201182    -1.785541  -1.386380   2.199543   1.525807   
1      154234      -0.349231     0.128667 -23.984747  16.697832 -22.209875   
2      173753      -0.209898     0.564650   0.345932  -0.024238  -0.249973   
3      222133       0.225693     1.011331  -3.613850  -0.922136  -4.749887   
4       15506       0.046539    -1.430146 -21.885434  12.930505 -24.098872   

         V4         V5        V6         V7  ...       V20        V21  \
0  2.954481   0.264425 -0.239757   0.953239  ... -0.131055   0.662084   
1  9.584969 -16.230439  2.596333 -33.239328  ...  5.804551 -12.615023   
2 -2.121791   0.461026 -0.265107   0.399168  ...  0.177209   0.557694   
3  3.373001  -0.545207 -1.171301  -4.172315  ... -0.320541   0.786787   
4  6.203314 -16.466099 -4.459842 -16.519836  ...  1.611998   1.762232   

        V22       V23       V24       V25       V26       V27       V28  Class  
0 -0.086671 -0.118522  0.700997  0.380318  0.197355 -0.896647 -0.409293      0  
1  5.774087  2.750221  0.513411 -1.608804 -0.459624 -4.626127 -0.334561      1  
2  1.489021 -0.219031  0.356435  0.070467 -0.027019 -0.007897 -0.016354      0  
3  0.893065  1.034907  0.097671 -1.345551 -0.788329  1.055442  0.099971      1  
4 -1.579055 -0.951043  0.134565  1.507110 -0.222671  1.527655  0.453699      1  

[5 rows x 32 columns]

In [40]:
df = df.drop(['Unnamed: 0'], axis = 1)

In [41]:
df.head()

scaled_amount  scaled_time         V1         V2         V3        V4  \
0      -0.201182    -1.785541  -1.386380   2.199543   1.525807  2.954481   
1      -0.349231     0.128667 -23.984747  16.697832 -22.209875  9.584969   
2      -0.209898     0.564650   0.345932  -0.024238  -0.249973 -2.121791   
3       0.225693     1.011331  -3.613850  -0.922136  -4.749887  3.373001   
4       0.046539    -1.430146 -21.885434  12.930505 -24.098872  6.203314   

          V5        V6         V7         V8  ...       V20        V21  \
0   0.264425 -0.239757   0.953239  -1.336626  ... -0.131055   0.662084   
1 -16.230439  2.596333 -33.239328 -21.560039  ...  5.804551 -12.615023   
2   0.461026 -0.265107   0.399168  -0.121305  ...  0.177209   0.557694   
3  -0.545207 -1.171301  -4.172315   1.517016  ... -0.320541   0.786787   
4 -16.466099 -4.459842 -16.519836  14.535565  ...  1.611998   1.762232   

        V22       V23       V24       V25       V26       V27       V28  Class  
0 -0.086671 -0.118522  0.700997  0.380318  0.197355 -0.896647 -0.409293      0  
1  5.774087  2.750221  0.513411 -1.608804 -0.459624 -4.626127 -0.334561      1  
2  1.489021 -0.219031  0.356435  0.070467 -0.027019 -0.007897 -0.016354      0  
3  0.893065  1.034907  0.097671 -1.345551 -0.788329  1.055442  0.099971      1  
4 -1.579055 -0.951043  0.134565  1.507110 -0.222671  1.527655  0.453699      1  

[5 rows x 31 columns]

In [42]:
df.shape

(984, 31)

In [43]:
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 24)

### Logistic Regression

In [62]:
lr_classifier = LogisticRegression(max_iter=1000,random_state=0)
lr_classifier.fit(X_train,y_train)

LogisticRegression(max_iter=1000, random_state=0)

In [63]:
y_pred = lr_classifier.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
cm

array([[86,  4],
       [10, 97]], dtype=int64)

In [64]:
accuracy_score(y_test, y_pred)

0.9289340101522843

### Decision Tree Classifier

In [65]:
dt_classifier= DecisionTreeClassifier(criterion='entropy', random_state=0)  
dt_classifier.fit(X_train, y_train)  

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [66]:
 y_pred= dt_classifier.predict(X_test)  

cm= confusion_matrix(y_test, y_pred)  
cm

array([[87,  3],
       [10, 97]], dtype=int64)

In [67]:
accuracy_score(y_test, y_pred)

0.934010152284264

### Random Forest

In [68]:
rf_classifier=RandomForestClassifier(n_estimators=20,criterion='entropy',random_state=0)
rf_classifier.fit(X_train,y_train)
y_pred=rf_classifier.predict(X_test)
  
cm= confusion_matrix(y_test, y_pred)  
cm

array([[87,  3],
       [10, 97]], dtype=int64)

In [69]:
accuracy_score(y_test, y_pred)

0.934010152284264

### Support Vector Classifier

In [70]:
#svclassifier=SVC(kernel='linear') accuracy=93%
svclassifier=SVC(kernel='poly')
svclassifier.fit(X_train,y_train)

SVC(kernel='poly')

In [71]:
y_pred=svclassifier.predict(X_test)
cm= confusion_matrix(y_test, y_pred)  
cm

array([[90,  0],
       [22, 85]], dtype=int64)

In [72]:
accuracy_score(y_test, y_pred)

0.8883248730964467