In [207]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
import numpy as np 

In [208]:
from sklearn.linear_model import LogisticRegression

In [209]:
df = pd.read_csv("creditcard_cleaned.csv")

In [210]:
df.head()

Unnamed: 0  scaled_amount  scaled_time         V1         V2         V3  \
0        7418      -0.201182    -1.785541  -1.386380   2.199543   1.525807   
1      154234      -0.349231     0.128667 -23.984747  16.697832 -22.209875   
2      173753      -0.209898     0.564650   0.345932  -0.024238  -0.249973   
3      222133       0.225693     1.011331  -3.613850  -0.922136  -4.749887   
4       15506       0.046539    -1.430146 -21.885434  12.930505 -24.098872   

         V4         V5        V6         V7  ...       V20        V21  \
0  2.954481   0.264425 -0.239757   0.953239  ... -0.131055   0.662084   
1  9.584969 -16.230439  2.596333 -33.239328  ...  5.804551 -12.615023   
2 -2.121791   0.461026 -0.265107   0.399168  ...  0.177209   0.557694   
3  3.373001  -0.545207 -1.171301  -4.172315  ... -0.320541   0.786787   
4  6.203314 -16.466099 -4.459842 -16.519836  ...  1.611998   1.762232   

        V22       V23       V24       V25       V26       V27       V28  Class  
0 -0.086671 -0.118522  0.700997  0.380318  0.197355 -0.896647 -0.409293      0  
1  5.774087  2.750221  0.513411 -1.608804 -0.459624 -4.626127 -0.334561      1  
2  1.489021 -0.219031  0.356435  0.070467 -0.027019 -0.007897 -0.016354      0  
3  0.893065  1.034907  0.097671 -1.345551 -0.788329  1.055442  0.099971      1  
4 -1.579055 -0.951043  0.134565  1.507110 -0.222671  1.527655  0.453699      1  

[5 rows x 32 columns]

In [211]:
df = df.drop(['Unnamed: 0'], axis = 1)

In [212]:
df.head()

scaled_amount  scaled_time         V1         V2         V3        V4  \
0      -0.201182    -1.785541  -1.386380   2.199543   1.525807  2.954481   
1      -0.349231     0.128667 -23.984747  16.697832 -22.209875  9.584969   
2      -0.209898     0.564650   0.345932  -0.024238  -0.249973 -2.121791   
3       0.225693     1.011331  -3.613850  -0.922136  -4.749887  3.373001   
4       0.046539    -1.430146 -21.885434  12.930505 -24.098872  6.203314   

          V5        V6         V7         V8  ...       V20        V21  \
0   0.264425 -0.239757   0.953239  -1.336626  ... -0.131055   0.662084   
1 -16.230439  2.596333 -33.239328 -21.560039  ...  5.804551 -12.615023   
2   0.461026 -0.265107   0.399168  -0.121305  ...  0.177209   0.557694   
3  -0.545207 -1.171301  -4.172315   1.517016  ... -0.320541   0.786787   
4 -16.466099 -4.459842 -16.519836  14.535565  ...  1.611998   1.762232   

        V22       V23       V24       V25       V26       V27       V28  Class  
0 -0.086671 -0.118522  0.700997  0.380318  0.197355 -0.896647 -0.409293      0  
1  5.774087  2.750221  0.513411 -1.608804 -0.459624 -4.626127 -0.334561      1  
2  1.489021 -0.219031  0.356435  0.070467 -0.027019 -0.007897 -0.016354      0  
3  0.893065  1.034907  0.097671 -1.345551 -0.788329  1.055442  0.099971      1  
4 -1.579055 -0.951043  0.134565  1.507110 -0.222671  1.527655  0.453699      1  

[5 rows x 31 columns]

In [213]:
X = df.iloc[ :, :-1].values
y = df.iloc[ :, -1].values

In [214]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 24)

## LogisticRegression 

In [215]:
lr = LogisticRegression(max_iter = 10000, random_state = 0)
lr.fit(X_train, y_train)

LogisticRegression(max_iter=10000, random_state=0)

In [216]:
y_pred = lr.predict(X_train)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_train, y_pred))

[[396   6]
 [ 33 352]]


In [217]:
from sklearn.metrics import accuracy_score
accuracy_score(y_train, y_pred)

0.9504447268106735

In [218]:
y_pred = lr.predict(X_test)

confusion_matrix(y_test, y_pred)

array([[86,  4],
       [10, 97]], dtype=int64)

In [219]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.9289340101522843

## LogisticRegressionCV ( cross-validation estimator)
#### Highest accuracy

In [220]:
from sklearn.linear_model import LogisticRegressionCV
clf = LogisticRegressionCV(max_iter = 10000, cv=5, random_state=0).fit(X_train, y_train)

In [221]:
y_pred = clf.predict(X_test)

confusion_matrix(y_test, y_pred)

array([[88,  2],
       [ 9, 98]], dtype=int64)

In [222]:
accuracy_score(y_test, y_pred)

0.9441624365482234

## LogisticRegression with MinMax Scaling

In [223]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range = (0,1))

scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [224]:
lr = LogisticRegression(max_iter = 10000, random_state = 0)
lr.fit(X_train, y_train)

LogisticRegression(max_iter=10000, random_state=0)

In [225]:
y_pred = lr.predict(X_test)

confusion_matrix(y_test, y_pred)

array([[90,  0],
       [15, 92]], dtype=int64)

In [226]:
accuracy_score(y_test, y_pred)

0.9238578680203046

## LogisticRegressionCV with MinMax Scaling

In [227]:
clf = LogisticRegressionCV(max_iter = 10000, cv=5, random_state=0).fit(X_train, y_train)

In [228]:
y_pred = clf.predict(X_test)

confusion_matrix(y_test, y_pred)

array([[87,  3],
       [10, 97]], dtype=int64)

In [229]:
accuracy_score(y_test, y_pred)

0.934010152284264

## LogisticRegression with  PowerTransformer Scaling

In [230]:
from sklearn.preprocessing import PowerTransformer
scalerPT = PowerTransformer(method='yeo-johnson')

scalerPT.fit(X_train)
X_train = scalerPT.transform(X_train)
X_test = scalerPT.transform(X_test)

In [231]:
lr = LogisticRegression(max_iter = 10000, random_state = 0)
lr.fit(X_train, y_train)

LogisticRegression(max_iter=10000, random_state=0)

In [232]:
y_pred = lr.predict(X_test)

confusion_matrix(y_test, y_pred)

array([[88,  2],
       [10, 97]], dtype=int64)

In [233]:
accuracy_score(y_test, y_pred)

0.9390862944162437

## LogisticRegressionCV with  PowerTransformer Scaling 

In [234]:
clf = LogisticRegressionCV(max_iter = 10000, cv=5, random_state=0).fit(X_train, y_train)

In [235]:
y_pred = clf.predict(X_test)

confusion_matrix(y_test, y_pred)

array([[88,  2],
       [10, 97]], dtype=int64)

In [236]:
accuracy_score(y_test, y_pred)

0.9390862944162437

## LogisticRegressionCV ( dropped scaled_time column ) 
#### Makes no difference

In [237]:
X = df.iloc[ :, ~df.columns.isin(['scaled_time', 'Class'])]#.values
y = df.iloc[ :, -1].values

In [238]:
X

scaled_amount         V1         V2         V3        V4         V5  \
0        -0.201182  -1.386380   2.199543   1.525807  2.954481   0.264425   
1        -0.349231 -23.984747  16.697832 -22.209875  9.584969 -16.230439   
2        -0.209898   0.345932  -0.024238  -0.249973 -2.121791   0.461026   
3         0.225693  -3.613850  -0.922136  -4.749887  3.373001  -0.545207   
4         0.046539 -21.885434  12.930505 -24.098872  6.203314 -16.466099   
..             ...        ...        ...        ...       ...        ...   
979      -0.321245   0.385108   1.217620  -1.953872  2.087076  -1.144225   
980      -0.349231   0.378275   3.914797  -5.726872  6.094141   1.698875   
981      -0.093314  -1.608599   2.492957   1.949613  4.522021  -0.854594   
982      -0.233487  -0.734303   0.435519  -0.530866 -0.471120   0.643214   
983       0.038623   1.227614  -0.668974  -0.271785 -0.589440  -0.604795   

           V6         V7         V8         V9  ...       V19       V20  \
0   -0.239757   0.953239  -1.336626  -0.447353  ...  0.649332 -0.131055   
1    2.596333 -33.239328 -21.560039 -10.842526  ... -1.243285  5.804551   
2   -0.265107   0.399168  -0.121305  -1.544817  ...  0.632515  0.177209   
3   -1.171301  -4.172315   1.517016  -1.775833  ...  1.987386 -0.320541   
4   -4.459842 -16.519836  14.535565  -3.897022  ...  1.104355  1.611998   
..        ...        ...        ...        ...  ...       ...       ...   
979 -0.576888  -2.582865   0.643230  -1.191233  ...  0.572791  0.380545   
980 -2.807314  -0.591118  -0.123496  -2.530713  ... -2.005477  0.440439   
981  1.289795  -0.739294  -3.242835  -1.287922  ...  0.556060 -0.567406   
982  0.713832  -1.234572  -2.551412  -2.057724  ...  2.502027  0.864536   
983 -0.350285  -0.486365  -0.010809  -0.794944  ...  1.190121  0.273799   

           V21       V22       V23       V24       V25       V26       V27  \
0     0.662084 -0.086671 -0.118522  0.700997  0.380318  0.197355 -0.896647   
1   -12.615023  5.774087  2.750221  0.513411 -1.608804 -0.459624 -4.626127   
2     0.557694  1.489021 -0.219031  0.356435  0.070467 -0.027019 -0.007897   
3     0.786787  0.893065  1.034907  0.097671 -1.345551 -0.788329  1.055442   
4     1.762232 -1.579055 -0.951043  0.134565  1.507110 -0.222671  1.527655   
..         ...       ...       ...       ...       ...       ...       ...   
979   0.594623  0.372144 -0.310456 -0.624065  0.840216 -0.159452  0.599482   
980   0.149896 -0.601967 -0.613724 -0.403114  1.568445  0.521884  0.527938   
981   3.463274  0.251718  0.231933  0.880244 -0.554212  0.434216 -0.122083   
982  -1.004877  1.150354 -0.152555 -1.386745  0.004716  0.219146 -0.058257   
983  -0.026055 -0.295255 -0.180459 -0.436539  0.494649 -0.283738 -0.001128   

          V28  
0   -0.409293  
1   -0.334561  
2   -0.016354  
3    0.099971  
4    0.453699  
..        ...  
979  0.288916  
980  0.411910  
981  0.202091  
982  0.158048  
983  0.035075  

[984 rows x 29 columns]

In [239]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 24)

In [240]:
clf = LogisticRegressionCV(max_iter = 10000, cv=5, random_state=0).fit(X_train, y_train)

In [241]:
y_pred = clf.predict(X_test)

confusion_matrix(y_test, y_pred)

array([[88,  2],
       [ 9, 98]], dtype=int64)

In [242]:
accuracy_score(y_test, y_pred)

0.9441624365482234

## LogisticRegressionCV ( dropped V20 to V28 column ) 
#### Drop in accuracy score 

In [243]:
X = df.iloc[ :, ~df.columns.isin(['V20', 'V21', 'V22', 'V23', 'V24','V25', 'V26','V27', 'V28','Class'])]#.values
y = df.iloc[ :, -1].values

In [244]:
X

scaled_amount  scaled_time         V1         V2         V3        V4  \
0        -0.201182    -1.785541  -1.386380   2.199543   1.525807  2.954481   
1        -0.349231     0.128667 -23.984747  16.697832 -22.209875  9.584969   
2        -0.209898     0.564650   0.345932  -0.024238  -0.249973 -2.121791   
3         0.225693     1.011331  -3.613850  -0.922136  -4.749887  3.373001   
4         0.046539    -1.430146 -21.885434  12.930505 -24.098872  6.203314   
..             ...          ...        ...        ...        ...       ...   
979      -0.321245    -0.871016   0.385108   1.217620  -1.953872  2.087076   
980      -0.349231    -1.763009   0.378275   3.914797  -5.726872  6.094141   
981      -0.093314    -0.147424  -1.608599   2.492957   1.949613  4.522021   
982      -0.233487    -0.405531  -0.734303   0.435519  -0.530866 -0.471120   
983       0.038623    -0.612488   1.227614  -0.668974  -0.271785 -0.589440   

            V5        V6         V7         V8  ...        V10       V11  \
0     0.264425 -0.239757   0.953239  -1.336626  ...   0.922799  1.011378   
1   -16.230439  2.596333 -33.239328 -21.560039  ... -19.836149  3.223233   
2     0.461026 -0.265107   0.399168  -0.121305  ...   0.337301  0.620181   
3    -0.545207 -1.171301  -4.172315   1.517016  ...  -3.754054  2.731576   
4   -16.466099 -4.459842 -16.519836  14.535565  ...  -8.650758  5.375434   
..         ...       ...        ...        ...  ...        ...       ...   
979  -1.144225 -0.576888  -2.582865   0.643230  ...  -3.095094  2.821145   
980   1.698875 -2.807314  -0.591118  -0.123496  ...  -5.153095  4.654088   
981  -0.854594  1.289795  -0.739294  -3.242835  ...   1.981092 -0.253495   
982   0.643214  0.713832  -1.234572  -2.551412  ...   0.166831  0.567552   
983  -0.604795 -0.350285  -0.486365  -0.010809  ...   0.264545  0.881268   

           V12       V13       V14       V15       V16        V17       V18  \
0    -2.273314  2.867908  1.498809  0.152471 -0.664465   0.951424 -0.147900   
1   -10.895134 -1.523452  0.116303 -3.098805 -7.606425 -18.108261 -7.511866   
2     0.076565  1.121529 -0.170874 -0.812162  1.272336  -0.488331 -0.567751   
3    -3.489375  1.547380 -4.571268 -0.517959 -4.239087  -9.250635 -2.434828   
4    -7.567214  0.461808 -7.827891 -0.022815 -6.578042 -13.002459 -4.884467   
..         ...       ...       ...       ...       ...        ...       ...   
979  -3.100546  0.146199 -4.510124  0.574490 -2.123463  -6.053319 -0.706376   
980  -7.839539  1.371819 -9.634690 -0.739597 -0.663204   0.891935  0.978676   
981   0.469117  1.252766 -0.386521  0.461747 -0.357709   0.627745  0.028496   
982  -0.858060 -0.448068 -0.264936  0.888863  0.838121   1.425060 -0.169664   
983  -0.324704 -0.263264 -1.112735 -0.540850  1.533411   0.831443 -0.473347   

          V19  
0    0.649332  
1   -1.243285  
2    0.632515  
3    1.987386  
4    1.104355  
..        ...  
979  0.572791  
980 -2.005477  
981  0.556060  
982  2.502027  
983  1.190121  

[984 rows x 21 columns]

In [245]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 24)

In [246]:
clf = LogisticRegressionCV(max_iter = 10000, cv=5, random_state=0).fit(X_train, y_train)

In [247]:
y_pred = clf.predict(X_test)

confusion_matrix(y_test, y_pred)

array([[87,  3],
       [ 9, 98]], dtype=int64)

In [248]:
accuracy_score(y_test, y_pred)

0.9390862944162437

## LogisticRegressionCV ( dropped scaled_amount column ) 
#### Makes no difference

In [249]:
X = df.iloc[ :, ~df.columns.isin(['scaled_amount', 'Class'])]#.values
y = df.iloc[ :, -1].values

In [250]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 24)

In [251]:
clf = LogisticRegressionCV(max_iter = 10000, cv=5, random_state=0).fit(X_train, y_train)

In [252]:
y_pred = clf.predict(X_test)

confusion_matrix(y_test, y_pred)

array([[88,  2],
       [ 9, 98]], dtype=int64)

In [253]:
accuracy_score(y_test, y_pred)

0.9441624365482234

## LogisticRegressionCV ( dropped all V column ) 
#### Drastic drop in score

In [254]:
X = df.iloc[ :, 0:1].values
y = df.iloc[ :, -1].values

In [255]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 24)

In [256]:
clf = LogisticRegressionCV(max_iter = 10000, cv=5, random_state=0).fit(X_train, y_train)

In [257]:
y_pred = clf.predict(X_test)

confusion_matrix(y_test, y_pred)

array([[84,  6],
       [80, 27]], dtype=int64)

In [258]:
accuracy_score(y_test, y_pred)

0.5634517766497462

## LogisticRegressionCV ( only V1 to V22 column )
#### Accuracy remains same

In [259]:
X = df.iloc[ :, 0:24].values    # 0:24 - 0.94416 ( V1 to V22)
                                # 0:23 - 0.93401 ( V1 to V21)
y = df.iloc[ :, -1].values

In [260]:
X

array([[ -0.20118218,  -1.78554051,  -1.38638048, ...,  -0.13105466,
          0.66208381,  -0.08667123],
       [ -0.34923131,   0.12866687, -23.98474665, ...,   5.80455066,
        -12.61502286,   5.77408727],
       [ -0.209898  ,   0.56465012,   0.34593206, ...,   0.17720937,
          0.55769395,   1.4890205 ],
       ...,
       [ -0.09331381,  -0.14742357,  -1.60859862, ...,  -0.56740584,
          3.46327354,   0.25171796],
       [ -0.23348671,  -0.40553054,  -0.73430316, ...,   0.86453612,
         -1.00487738,   1.15035359],
       [  0.03862303,  -0.61248781,   1.22761441, ...,   0.27379921,
         -0.02605472,  -0.29525477]])

In [261]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 24)

In [262]:
clf = LogisticRegressionCV(max_iter = 10000, cv=5, random_state=0).fit(X_train, y_train)

In [263]:
y_pred = clf.predict(X_test)

confusion_matrix(y_test, y_pred)

array([[88,  2],
       [ 9, 98]], dtype=int64)

In [264]:
accuracy_score(y_test, y_pred)

0.9441624365482234